name: Build Docker image
on:
  push:
    branches:
      - main
      - test
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Run the build
        run: |
          export DATE=$(date +%Y%m%d)
          export LOGIN=$GITHUB_REPOSITORY_OWNER
          export IMAGE=$GITHUB_REPOSITORY

          pip install requests
          python ./complete_template.py Dockerfile.template Dockerfile

          echo $PASSWORD | docker login $REGISTRY -u $LOGIN --password-stdin

          docker build . --tag $REGISTRY/$IMAGE:$DATE --tag $REGISTRY/$IMAGE:latest
          docker push $REGISTRY/$IMAGE:latest
          docker push $REGISTRY/$IMAGE:$DATE
        env:
          REGISTRY: ghcr.io
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}

